export const context1 = [
    { name: "Pierwsze auto", link: "http://skoda-safety.wp.pl/artykul/czy-male-i-nowoczesne-auta-sa-bezpieczniejsze-niz-wieksze-i-starsze", context: "Zastanawiasz się nad pierwszym autem i chciałbyś, żeby było bezpieczne? A może chcesz dowiedzieć się o nowinkach motoryzacyjnych. To jest artykuł, w którym są poruszane najważniejsze kwestie bezpieczeństwa auta od reflektorów po nowoczesne systemy wspomagania kierowcy."},
    { name: "Samochody elektrczyne są bezpieczne?", link: "https://forsal.pl/artykuly/1430650,impact-czy-samochody-elektryczne-sa-bezpieczniejsze-od-samochodow-spalinowych.html", context: "Chciałbyś zaczerpnąć wiedzy na  temat bezpieczeństwa samochodów elektrycznych? Chciałbyś zobaczyć twarde statystyki? O to artykuł doskonały dla ciebie! Znajdziesz tutaj informacje na temat pożarów samochodów elektrycznych oraz crash testach." },
    { name: "Statystyki", link: "https://knaufautomotive.com/pl/jak-samochody-elektryczne-poprawiaja-bezpieczenstwo-na-drogach/", context: "Chciałbyś poznać statystyki na temat bezpieczeństwa oraz wypadków samochodów elektrycznych? A może dowiedzieć się jak budowa samochodu elektrycznego wpływa na bezpieczeństwo? Jeżeli tak, to jest artykuł doskonały właśnie dla ciebie!" },
    { name: "Kupno elektryka? Nic prostszego!", link: "https://e.autokult.pl/34235,samochody-elektryczne-dla-opornych-przedstawiamy-fakty-obalamy-mity", context: "Chcesz kupić elektryka, ale nie wiesz czy się opłaca? A może chciałbyś porównać koszta użytkowana? To jest artykuł dla ciebie! Znajdziesz tutaj wszystkie ważne informacje na temat elektryków." },
    { name: "Nowinki technologiczne", link: "https://www.autoexpert.pl/artykuly/wplyw-nowych-technologii-na-bezpieczenstwo-jazdy-samochodow", context: "Chciałbyś wiedzieć o nowinkach technologicznych w branży motoryzacyjnej? A może ciekawisz się jak udoskonalić swoją jazdę? Jeśli tak, to jak najszybciej musisz przeczytać właśnie ten artykuł!" },
    { name: "Bezpieczeństwo w pigułce", link: "https://mojafirma.infor.pl/moto/eksploatacja-auta/porady-uzytkowe/697553,Co-w-samochodzie-odpowiada-za-bezpieczenstwo-pasazerow.html", context: "W tym artykule jest opisane bezpieczeństwo w pigułce. Chciałbyś poznać twarde fakty o systemach wspomagających kierowcę albo co chroni kierowcę i pasażerów podczas jazdy? To jest ten artykuł, który powinieneś przeczytać!" },
]
export const context2 = [
    { name: "Wpływ elektryków na środowisko", link: "https://www.autocentrum.pl/newsy/samochody-elektryczne-bardziej-ekologiczne-nawet-dwu-trzykrotnie/", context: "Masz wątpliwości czy samochody napędzane energią elektryczną rzeczywiście mają pozytywny wpływ na środowisko? Ten artykuł przekonuje, że jest inaczej! "},
    { name: "Czy samochody elektryczne są ekologiczne?", link: "https://zmienimyswiat.pl/2020/01/13/czy-samochody-elektryczne-sa-ekologiczne/", context: "Artykuł ten opisuje wpływ pojazdów elektrycznych na ekologię oraz konieczność ratowania naszej planety ze względu na wyniszczający wpływ smogu na klimat." },
    { name: "Czy polskie auta elektryczne jeżdżą na węgiel?", link: "https://moto.pl/MotoPL/7,174430,25666877,czy-samochod-elektryczny-jest-ekologiczny-moto-2030.html", context: " Nie wszystkie kraje na świecie pozyskują energię elektryczną w sposób ekologiczny. Niektóre - tak jak polska - palą węgiel aby ją pozyskać. Czy to czyni samochody elektryczne tak samo zgubnymi dla środowiska jak auta spalinowe? " },
    { name: "'Czystość' samochodów elektrycznych w praktyce", link: "https://dopower.pl/news/samochody-elektryczne-a-ekologia/", context: "Czy elektryki będą w pełni 'czyste'? Odpowiedź nie jest jednoznaczna, przekonaj się o wpływie samochodów elektrycznych na środowisko!" },
    { name: " Brukselskie badania na temat ekologiczności elektryków ", link: "https://biznesalert.pl/transport-environment-samochody-elektryczne-srodowisko-benzyna-diesel-elektromobilnosc/", context: " Analiza analityków dotycząca emicji CO2 przez samochody. " },
    { name: "Emisja szkodliwych substancji", link: "https://motoryzacja.interia.pl/raporty/raport-era-elektromobilnosci/artykuly/news-dlaczego-samochody-elektryczne-sa-najbardziej-przyjazne-srod,nId,3055953", context: "Przekonaj się czy rzeczywiście samochody elektryczne emitują mniej substancji zgubnych dla środowiska!" },
]